/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurante;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import restaurante.bd.Conexao;

/**
 *
 * @author gustavo
 */
public class ViewPedido extends javax.swing.JFrame {

    private Conexao bd = new Conexao();
    private Produto produto = new Produto();
    private Pedido pedido = new Pedido();
    /**
     * Creates new form ViewPedido
     */
    public ViewPedido() {
        initComponents();
        bd.setCon();
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing (WindowEvent e){
                try {
                    bd.closeCon();
                } catch (SQLException ex) {
                    Logger.getLogger(ViewPedido.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    private void editarDetalhes(String foto,String desc, String valor){
        fotoItem.setIcon(new ImageIcon(this.getClass().getResource("/"+foto)));
        descItem.setText("<html>"+desc+"</html>");
        precoItem.setText("R$ "+valor);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fotoItem = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        descItem = new javax.swing.JLabel();
        precoItem = new javax.swing.JLabel();
        panelSlc4 = new javax.swing.JPanel();
        btnSelect4 = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        panelSlc3 = new javax.swing.JPanel();
        btnSelect3 = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        panelSlc2 = new javax.swing.JPanel();
        btnSelect2 = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        panelSlc8 = new javax.swing.JPanel();
        btnSelect8 = new javax.swing.JToggleButton();
        jLabel11 = new javax.swing.JLabel();
        panelSlc7 = new javax.swing.JPanel();
        btnSelect7 = new javax.swing.JToggleButton();
        jLabel9 = new javax.swing.JLabel();
        panelSlc6 = new javax.swing.JPanel();
        btnSelect6 = new javax.swing.JToggleButton();
        jLabel10 = new javax.swing.JLabel();
        panelSlc5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnSelect5 = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();
        panelSlc1 = new javax.swing.JPanel();
        btnSelect1 = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(211, 211, 211));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 972, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descrição", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Foto do item");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        fotoItem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fotoItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/item.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fotoItem, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(155, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(fotoItem, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Ingredientes, Valor do item");

        descItem.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        descItem.setForeground(new java.awt.Color(101, 101, 101));
        descItem.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        descItem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        precoItem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        precoItem.setForeground(new java.awt.Color(255, 0, 0));
        precoItem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        precoItem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descItem, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precoItem, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descItem, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(precoItem, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelSlc4.setPreferredSize(new java.awt.Dimension(160, 170));

        btnSelect4.setText("Selecionar");
        btnSelect4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelect4ActionPerformed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Expresso-Delivery_7f5ed1df30a43062cd9a8f61a28148fb.jpg"))); // NOI18N

        javax.swing.GroupLayout panelSlc4Layout = new javax.swing.GroupLayout(panelSlc4);
        panelSlc4.setLayout(panelSlc4Layout);
        panelSlc4Layout.setHorizontalGroup(
            panelSlc4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSelect4, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        panelSlc4Layout.setVerticalGroup(
            panelSlc4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSlc4Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSelect4))
        );

        panelSlc3.setPreferredSize(new java.awt.Dimension(160, 170));

        btnSelect3.setText("Selecionar");
        btnSelect3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelect3ActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Expresso-Delivery_2808b351c161284331ef6736f138078d.jpg"))); // NOI18N

        javax.swing.GroupLayout panelSlc3Layout = new javax.swing.GroupLayout(panelSlc3);
        panelSlc3.setLayout(panelSlc3Layout);
        panelSlc3Layout.setHorizontalGroup(
            panelSlc3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSelect3, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        panelSlc3Layout.setVerticalGroup(
            panelSlc3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSlc3Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSelect3))
        );

        panelSlc2.setPreferredSize(new java.awt.Dimension(160, 170));

        btnSelect2.setText("Selecionar");
        btnSelect2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelect2ActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Expresso-Delivery_12bbef384d58de2789d71456d90e7973.jpg"))); // NOI18N

        javax.swing.GroupLayout panelSlc2Layout = new javax.swing.GroupLayout(panelSlc2);
        panelSlc2.setLayout(panelSlc2Layout);
        panelSlc2Layout.setHorizontalGroup(
            panelSlc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSelect2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        panelSlc2Layout.setVerticalGroup(
            panelSlc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSlc2Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSelect2))
        );

        panelSlc8.setPreferredSize(new java.awt.Dimension(160, 170));

        btnSelect8.setText("Selecionar");
        btnSelect8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelect8ActionPerformed(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Expresso-Delivery_546c150581f3a84bbf39608b4ed37551.png"))); // NOI18N

        javax.swing.GroupLayout panelSlc8Layout = new javax.swing.GroupLayout(panelSlc8);
        panelSlc8.setLayout(panelSlc8Layout);
        panelSlc8Layout.setHorizontalGroup(
            panelSlc8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSelect8, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        panelSlc8Layout.setVerticalGroup(
            panelSlc8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSlc8Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(btnSelect8))
        );

        panelSlc7.setPreferredSize(new java.awt.Dimension(160, 170));

        btnSelect7.setText("Selecionar");
        btnSelect7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelect7ActionPerformed(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Expresso-Delivery_c5fd0c57eac60490f7c3b405a180c5ea.png"))); // NOI18N

        javax.swing.GroupLayout panelSlc7Layout = new javax.swing.GroupLayout(panelSlc7);
        panelSlc7.setLayout(panelSlc7Layout);
        panelSlc7Layout.setHorizontalGroup(
            panelSlc7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSelect7, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        panelSlc7Layout.setVerticalGroup(
            panelSlc7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSlc7Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSelect7))
        );

        panelSlc6.setPreferredSize(new java.awt.Dimension(160, 170));

        btnSelect6.setText("Selecionar");
        btnSelect6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelect6ActionPerformed(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Expresso-Delivery_a1455ddd2dff1ee61b1ce1e56cf05317.png"))); // NOI18N

        javax.swing.GroupLayout panelSlc6Layout = new javax.swing.GroupLayout(panelSlc6);
        panelSlc6.setLayout(panelSlc6Layout);
        panelSlc6Layout.setHorizontalGroup(
            panelSlc6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSelect6, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        panelSlc6Layout.setVerticalGroup(
            panelSlc6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSlc6Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSelect6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelSlc5.setPreferredSize(new java.awt.Dimension(160, 170));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Expresso-Delivery_9f0a112a57c9f1c8d9159cf34cafd573.png"))); // NOI18N

        btnSelect5.setText("Selecionar");
        btnSelect5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelect5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSlc5Layout = new javax.swing.GroupLayout(panelSlc5);
        panelSlc5.setLayout(panelSlc5Layout);
        panelSlc5Layout.setHorizontalGroup(
            panelSlc5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 160, Short.MAX_VALUE)
            .addComponent(btnSelect5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelSlc5Layout.setVerticalGroup(
            panelSlc5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSlc5Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSelect5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jButton2.setText("Comprar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        panelSlc1.setPreferredSize(new java.awt.Dimension(160, 170));

        btnSelect1.setText("Selecionar");
        btnSelect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelect1ActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Expresso-Delivery_10bea64b80d31677828a1723d1bd065c.jpg"))); // NOI18N

        javax.swing.GroupLayout panelSlc1Layout = new javax.swing.GroupLayout(panelSlc1);
        panelSlc1.setLayout(panelSlc1Layout);
        panelSlc1Layout.setHorizontalGroup(
            panelSlc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSelect1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        panelSlc1Layout.setVerticalGroup(
            panelSlc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSlc1Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSelect1))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelSlc5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelSlc6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelSlc7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelSlc8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelSlc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(panelSlc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelSlc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelSlc4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelSlc4, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(panelSlc3, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(panelSlc2, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(panelSlc1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelSlc8, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(panelSlc7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(panelSlc6, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(panelSlc5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelect1ActionPerformed
        // TODO add your handling code here:
        try {
            ResultSet res = produto.select(bd.getCon(), 1);
            res.first();
            editarDetalhes(res.getString("foto_p"), res.getString("descricao_p"), res.getString("valor_p"));
        } catch (SQLException ex) {
            Logger.getLogger(ViewPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSelect1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Inicio In = new Inicio();
        In.setVisible(true);
        try {
            bd.closeCon();
        } catch (SQLException ex) {
            Logger.getLogger(ViewPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSelect2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelect2ActionPerformed
        // TODO add your handling code here:
        try {
            ResultSet res = produto.select(bd.getCon(), 2);
            res.first();
            editarDetalhes(res.getString("foto_p"), res.getString("descricao_p"), res.getString("valor_p"));
        } catch (SQLException ex) {
            Logger.getLogger(ViewPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSelect2ActionPerformed

    private void btnSelect3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelect3ActionPerformed
        try {
            ResultSet res = produto.select(bd.getCon(), 3);
            res.first();
            editarDetalhes(res.getString("foto_p"), res.getString("descricao_p"), res.getString("valor_p"));
        } catch (SQLException ex) {
            Logger.getLogger(ViewPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSelect3ActionPerformed

    private void btnSelect4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelect4ActionPerformed
       try {
            ResultSet res = produto.select(bd.getCon(), 4);
            res.first();
            editarDetalhes(res.getString("foto_p"), res.getString("descricao_p"), res.getString("valor_p"));
        } catch (SQLException ex) {
            Logger.getLogger(ViewPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSelect4ActionPerformed

    private void btnSelect5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelect5ActionPerformed
        try {
            ResultSet res = produto.select(bd.getCon(), 5);
            res.first();
            editarDetalhes(res.getString("foto_p"), res.getString("descricao_p"), res.getString("valor_p"));
        } catch (SQLException ex) {
            Logger.getLogger(ViewPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSelect5ActionPerformed

    private void btnSelect6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelect6ActionPerformed
        try {
            ResultSet res = produto.select(bd.getCon(), 6);
            res.first();
            editarDetalhes(res.getString("foto_p"), res.getString("descricao_p"), res.getString("valor_p"));
        } catch (SQLException ex) {
            Logger.getLogger(ViewPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSelect6ActionPerformed

    private void btnSelect7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelect7ActionPerformed
        try {
            ResultSet res = produto.select(bd.getCon(), 7);
            res.first();
            editarDetalhes(res.getString("foto_p"), res.getString("descricao_p"), res.getString("valor_p"));
        } catch (SQLException ex) {
            Logger.getLogger(ViewPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSelect7ActionPerformed

    private void btnSelect8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelect8ActionPerformed
        try {
            ResultSet res = produto.select(bd.getCon(), 5);
            res.first();
            editarDetalhes(res.getString("foto_p"), res.getString("descricao_p"), res.getString("valor_p"));
        } catch (SQLException ex) {
            Logger.getLogger(ViewPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSelect8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        boolean sl1 = btnSelect1.isSelected();
        boolean sl2 = btnSelect2.isSelected();
        boolean sl3 = btnSelect3.isSelected();
        boolean sl4 = btnSelect4.isSelected();
        boolean sl5 = btnSelect5.isSelected();
        boolean sl6 = btnSelect6.isSelected();
        boolean sl7 = btnSelect7.isSelected();
        boolean sl8 = btnSelect8.isSelected();
        double valorTotal = 0.0;
        int produtos_id[] = {0,0,0,0,0,0,0,0};
        int num_pedido = 0;
        String produtosp = "";
        if(sl1 || sl2 || sl3 || sl4 || sl5 || sl6 || sl7 || sl8){
            if(sl1){
               ResultSet res;
                try {
                    res = produto.select(bd.getCon(), 1);
                    res.first();
                    valorTotal += res.getDouble("valor_p");
                    produtos_id[0] = res.getInt("id_produto");
                    produtosp += "- "+res.getString("nome_p")+"\n";
                } catch (SQLException ex) {
                    Logger.getLogger(ViewPedido.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if(sl2){
               ResultSet res;
                try {
                    res = produto.select(bd.getCon(), 2);
                    res.first();
                    valorTotal += res.getDouble("valor_p");
                    produtos_id[1] = res.getInt("id_produto");
                    produtosp += "- "+res.getString("nome_p")+"\n";
                } catch (SQLException ex) {
                    Logger.getLogger(ViewPedido.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if(sl3){
               ResultSet res;
                try {
                    res = produto.select(bd.getCon(), 3);
                    res.first();
                    valorTotal += res.getDouble("valor_p");
                    produtos_id[2] = res.getInt("id_produto");
                     produtosp += "- "+res.getString("nome_p")+"\n";
                } catch (SQLException ex) {
                    Logger.getLogger(ViewPedido.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if(sl4){
               ResultSet res;
                try {
                    res = produto.select(bd.getCon(), 4);
                    res.first();
                    valorTotal += res.getDouble("valor_p");
                    produtos_id[3] = res.getInt("id_produto");
                    produtosp += "- "+res.getString("nome_p")+"\n";
                } catch (SQLException ex) {
                    Logger.getLogger(ViewPedido.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if(sl5){
               ResultSet res;
                try {
                    res = produto.select(bd.getCon(), 5);
                    res.first();
                    valorTotal += res.getDouble("valor_p");
                    produtos_id[4] = res.getInt("id_produto");
                    produtosp += "- "+res.getString("nome_p")+"\n";
                } catch (SQLException ex) {
                    Logger.getLogger(ViewPedido.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if(sl6){
               ResultSet res;
                try {
                    res = produto.select(bd.getCon(), 6);
                    res.first();
                    valorTotal += res.getDouble("valor_p");
                    produtos_id[5] = res.getInt("id_produto");
                    produtosp += "- "+res.getString("nome_p")+"\n";
                } catch (SQLException ex) {
                    Logger.getLogger(ViewPedido.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if(sl7){
               ResultSet res;
                try {
                    res = produto.select(bd.getCon(), 7);
                    res.first();
                    valorTotal += res.getDouble("valor_p");
                    produtos_id[6] = res.getInt("id_produto");
                    produtosp += "- "+res.getString("nome_p")+"\n";
                } catch (SQLException ex) {
                    Logger.getLogger(ViewPedido.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if(sl8){
               ResultSet res;
                try {
                    res = produto.select(bd.getCon(), 8);
                    res.first();
                    valorTotal += res.getDouble("valor_p");
                    produtos_id[7] = res.getInt("id_produto");
                    produtosp += "- "+res.getString("nome_p")+"\n";
                } catch (SQLException ex) {
                    Logger.getLogger(ViewPedido.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            try {
                num_pedido = pedido.insertPedido(bd.getCon(), Math.ceil(valorTotal), 1);
            } catch (SQLException ex) {
                Logger.getLogger(ViewPedido.class.getName()).log(Level.SEVERE, null, ex);
            }
            for(int i=0;i < produtos_id.length;i++){
                if(produtos_id[i] > 0){
                    try {
                        pedido.insertProdutoxPedido(bd.getCon(), num_pedido, produtos_id[i]);
                    } catch (SQLException ex) {
                        Logger.getLogger(ViewPedido.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            JOptionPane.showMessageDialog(this, "Pedido realizado com sucesso!\n\nO seu pedido é composto por:\n"+
                    produtosp+"\n\nO valor total a ser pago é: R$ "+
                    Math.ceil(valorTotal)+"\nO numero do pedido é: ( `"+
                    num_pedido+"` ) guarde ele para o acompanhar!", "Sucesso!",JOptionPane.INFORMATION_MESSAGE);
            Inicio In = new Inicio();
            In.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Você deve selecionar pelo menos um produto!", "Atenção",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPedido().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnSelect1;
    private javax.swing.JToggleButton btnSelect2;
    private javax.swing.JToggleButton btnSelect3;
    private javax.swing.JToggleButton btnSelect4;
    private javax.swing.JToggleButton btnSelect5;
    private javax.swing.JToggleButton btnSelect6;
    private javax.swing.JToggleButton btnSelect7;
    private javax.swing.JToggleButton btnSelect8;
    private javax.swing.JLabel descItem;
    private javax.swing.JLabel fotoItem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel panelSlc1;
    private javax.swing.JPanel panelSlc2;
    private javax.swing.JPanel panelSlc3;
    private javax.swing.JPanel panelSlc4;
    private javax.swing.JPanel panelSlc5;
    private javax.swing.JPanel panelSlc6;
    private javax.swing.JPanel panelSlc7;
    private javax.swing.JPanel panelSlc8;
    private javax.swing.JLabel precoItem;
    // End of variables declaration//GEN-END:variables
}
